import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import vm from 'node:vm'
import test from 'node:test'
import { renderClientBundle } from '../bundle/geoharness-bundle/scripts/build-client.mjs'

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const bundleRoot = join(repositoryRoot, 'bundle', 'geoharness-bundle')
const packageName = '@geoharness/harness-plugin'

test('the generated client artifact is reproducible from typed source and CSS', async () => {
  const expected = await renderClientBundle()
  const actual = await readFile(join(bundleRoot, 'client.js'), 'utf8')
  assert.equal(actual, expected)
  assert.match(actual, /Generated by scripts\/build-client\.mjs/)
  assert.match(actual, /data-geoharness-phase/)
})

test('Phase 1 UI shell surfaces remain present as later phases extend the workspace', async () => {
  const source = await readFile(join(bundleRoot, 'src', 'client.tsx'), 'utf8')
  const styles = await readFile(join(bundleRoot, 'src', 'styles.css'), 'utf8')
  for (const label of [
    'GeoHarness', 'Map workspace', 'Layer panel', 'Agent workspace',
    'Describe your spatial goal', 'Native Harness Agent', 'LIVE AGENT TOOL TRACE',
    'HARNESS SETTINGS', 'API keys · model providers',
  ]) assert.match(source, new RegExp(label, 'i'))
  assert.match(styles, /grid-template-columns: 236px minmax\(340px, 1fr\) 304px/)
  assert.match(styles, /--dsw-alias-bg-base/)
  assert.match(styles, /--dsw-alias-state-business-primary/)
  assert.match(styles, /border-radius: 14px/)
  assert.match(styles, /box-shadow: var\(--dsw-shadow-lv2\)/)
  assert.doesNotMatch(source, /name: 'conversation(?:\.|')/)
  assert.match(source, /name: 'root'/)
  assert.match(source, /priority: -100/)
  assert.match(source, /connection\.api\.settings\.describe/)
  assert.match(source, /connection\.api\.llm\.providers/)
  assert.match(source, /connection\.api\.credentials\.(describe|set)/)
  assert.match(source, /type="password"/)
  assert.doesNotMatch(source, /conversation\.session\.header\.actions|shell\.overlay/)
  assert.doesNotMatch(source, /ctx\.tools|\/api\/geo|FastAPI/i)
  assert.match(source, /connection\.api\.sessions\.prompt/)
  assert.match(source, /agent\/workspace/)
  assert.match(source, /AGENT RESULT/)
  assert.match(source, /projectAgentHistory/)
  assert.doesNotMatch(source, /SCENARIOS|goal\/start|scenario\/progress|Example|expectedResult/)
  assert.equal((source.match(/执行 GIS 任务/g) ?? []).length, 1)
  assert.doesNotMatch(source, /Run current input|gh-run-button/)
})

test('the generated factory replaces the Harness root Slot with the GeoHarness shell', async () => {
  const code = await readFile(join(bundleRoot, 'client.js'), 'utf8')
  let registration
  const appendedStyles = []
  const document = {
    querySelector: () => null,
    createElement: () => ({ dataset: {}, textContent: '' }),
    head: { appendChild: node => appendedStyles.push(node) },
  }
  const window = { __ModuleLoader__: { load: value => { registration = value } } }
  vm.runInNewContext(code, { document, window }, { filename: 'client.js' })
  assert.equal(registration.id, packageName)

  const fragment = Symbol('fragment')
  const jsx = (type, props, key) => ({ type, props: props ?? {}, key })
  const React = {
    useEffect: effect => { effect() },
    useMemo: factory => factory(),
    useRef: initial => ({ current: initial }),
    useState: initial => [typeof initial === 'function' ? initial() : initial, () => {}],
  }
  const plugin = registration.factory(specifier => {
    if (specifier === 'react') return React
    if (specifier === 'react/jsx-runtime') return { Fragment: fragment, jsx, jsxs: jsx }
    throw new Error(`unexpected external: ${specifier}`)
  })
  assert.deepEqual([...plugin.inject], ['slots', 'connection'])
  assert.equal(plugin.credentialRef('deepseek-official', { apiKeyEnv: 'DEEPSEEK_API_KEY' }), 'DEEPSEEK_API_KEY')
  assert.equal(plugin.credentialRef('ustc', undefined), 'USTC_API_KEY')
  assert.deepEqual(JSON.parse(JSON.stringify(plugin.settingAtPath({
    providers: { ustc: { apiKeyEnv: 'USTC_API_KEY' } },
  }, ['providers', 'ustc']))), { apiKeyEnv: 'USTC_API_KEY' })

  const slots = []
  plugin.apply({
    slots: {
      register: (options, component) => { slots.push({ options, component }); return () => {} },
    },
    connection: {
      api: { sessions: {} },
      rpc: {},
    },
  })
  assert.deepEqual(
    slots.map(slot => ({ name: slot.options.name, priority: slot.options.priority })),
    [{ name: 'root', priority: -100 }],
  )
  assert.equal(appendedStyles.length, 1)
  assert.match(appendedStyles[0].textContent, /\.gh-shell/)

  const shell = slots[0].component(slots[0].options.inject())
  assert.equal(shell.props['data-geoharness-plugin'], 'loaded')
  assert.equal(shell.props['data-geoharness-agent'], 'native')
  assert.equal(shell.type, 'main')
})
