import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import vm from 'node:vm'
import test from 'node:test'
import { renderClientBundle } from '../bundle/geoharness-bundle/scripts/build-client.mjs'

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const bundleRoot = join(repositoryRoot, 'bundle', 'geoharness-bundle')
const packageName = '@geoharness/harness-plugin'

test('the generated client artifact is reproducible from typed source and CSS', async () => {
  const expected = await renderClientBundle()
  const actual = await readFile(join(bundleRoot, 'client.js'), 'utf8')
  assert.equal(actual, expected)
  assert.match(actual, /Generated by scripts\/build-client\.mjs/)
  assert.match(actual, /data-geoharness-phase/)
})

test('Phase 1 UI shell surfaces remain present as later phases extend the workspace', async () => {
  const source = await readFile(join(bundleRoot, 'src', 'client.tsx'), 'utf8')
  const styles = await readFile(join(bundleRoot, 'src', 'styles.css'), 'utf8')
  for (const label of [
    'GeoHarness', 'Map workspace', 'Layer panel', 'Agent workspace',
    'Describe your spatial goal', 'Scenario',
  ]) assert.match(source, new RegExp(label, 'i'))
  for (const id of [
    '01-building-data-inspection', '02-river-building-query',
    '03-building-statistics-by-district', '04-road-accessibility',
    '05-parameter-revision', '06-multi-constraint-selection',
    '07-official-nyc-building-inspection',
  ]) assert.match(source, new RegExp(id))
  assert.match(styles, /grid-template-columns: 228px minmax\(340px, 1fr\) 286px/)
  assert.doesNotMatch(source, /ctx\.tools|\/api\/geo|FastAPI/i)
})

test('the generated factory registers the shell through additive Harness Slots', async () => {
  const code = await readFile(join(bundleRoot, 'client.js'), 'utf8')
  let registration
  const appendedStyles = []
  const document = {
    querySelector: () => null,
    createElement: () => ({ dataset: {}, textContent: '' }),
    head: { appendChild: node => appendedStyles.push(node) },
  }
  const window = { __ModuleLoader__: { load: value => { registration = value } } }
  vm.runInNewContext(code, { document, window }, { filename: 'client.js' })
  assert.equal(registration.id, packageName)

  const fragment = Symbol('fragment')
  const jsx = (type, props, key) => ({ type, props: props ?? {}, key })
  const React = {
    useMemo: factory => factory(),
    useRef: initial => ({ current: initial }),
    useState: initial => [typeof initial === 'function' ? initial() : initial, () => {}],
  }
  const plugin = registration.factory(specifier => {
    if (specifier === 'react') return React
    if (specifier === 'react/jsx-runtime') return { Fragment: fragment, jsx, jsxs: jsx }
    throw new Error(`unexpected external: ${specifier}`)
  })
  assert.deepEqual([...plugin.inject], ['slots', 'connection'])

  const awaited = []
  const slots = []
  plugin.apply({
    slots: {
      inject: (name, setup) => { awaited.push(name); return setup() },
      register: (options, component) => { slots.push({ options, component }); return () => {} },
    },
  })
  assert.deepEqual(awaited, ['conversation.view', 'shell.overlay'])
  assert.deepEqual(slots.map(slot => slot.options.id), ['geoharness', 'geoharness-brand'])
  assert.equal(appendedStyles.length, 1)
  assert.match(appendedStyles[0].textContent, /\.gh-shell/)

  const shell = slots[0].component()
  assert.ok(Number(shell.props['data-geoharness-phase']) >= 1)
  const badge = slots[1].component()
  assert.equal(badge.props['data-geoharness-plugin'], 'loaded')
})
